[custom]
; lib_deps=
;   frankboesing/FastCRC
;   https://github.com/ab-tools/lz4.git
;   https://github.com/ab-tools/PN7160
build_flags =
  ${KNX_TP.build_flags}
  -D OPENKNX_LOOPTIME_WARNING=100
  -D PN7160_RP2040

[custom_develop]
extends = custom
build_flags = 
  ${custom.build_flags}
  -D OPENKNX_HEARTBEAT
debug_build_flags = 
  ${OPENKNX_DEBUG.build_flags}
  -ggdb3
  -D OPENKNX_HEARTBEAT


[RP2040_FLASH]
build_flags =
  -D KNX_FLASH_SIZE=0x20000
  -D KNX_FLASH_OFFSET=0x140000
  -D OPENKNX_FLASH_SIZE=0x4000
  -D OPENKNX_FLASH_OFFSET=0x160000
  -D FINGERPRINT_FLASH_SIZE=0x11000
  -D FINGERPRINT_FLASH_OFFSET=0x12F000
  -D NFC_FLASH_SIZE=0x11000
  -D NFC_FLASH_OFFSET=0x11E000
  -D KEYPAD_FLASH_SIZE=0x11000
  -D KEYPAD_FLASH_OFFSET=0x10D000

[RP2040_custom]
extends = RP2040, RP2040_16MB, custom
board_build.filesystem_size = 15314944
build_flags = 
  -D SERIAL_DEBUG=Serial
  -D USE_KNX_DMA_UART=0
  -D USE_KNX_DMA_IRQ=0
  -D MAX_TX_QUEUE=100
  -D MAX_RX_QUEUE_BYTES=1024
  -Wunused-variable

[RP2040_custom_develop]
extends = RP2040_develop, RP2040_custom, custom_develop
build_flags = 
  ${RP2040_develop.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_develop.build_flags}
  ;-D BOARD_AB_SMARTHOUSE_FINGERPRINT_V13
  -D DEVICE_UP1_SEN_8X
  ;-D USE_DATASECURE
debug_build_flags = 
  ${custom_develop.debug_build_flags}
  -O0

[RP2040_custom_releases]
extends = RP2040_releases, RP2040_custom, custom
build_flags = 
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom.build_flags}

[env:debug_RP2040]
extends = RP2040_custom_develop

[env:upload_JLINK_RP2040]
extends = RP2040_custom_develop, UPLOAD_JLINK

[env:release_R503]
extends = RP2040_custom_releases
build_flags = 
  ${RP2040_custom_releases.build_flags}
  -D BOARD_AB_SMARTHOUSE_FINGERPRINT_V13
debug_build_flags =
  ${RP2040_custom_develop.debug_build_flags}

[env:release_R503Pro]
extends = RP2040_custom_releases
build_flags = 
  ${RP2040_custom_releases.build_flags}
  -D BOARD_AB_SMARTHOUSE_FINGERPRINT_V13

[env:release_VAC_REG1]
extends = RP2040_custom_releases
build_flags = 
  ${RP2040_custom_releases.build_flags}
  -D OKNXHW_REG1_BASE_V1

[env:release_UP1]
extends = RP2040_custom_releases
build_flags = 
  ${RP2040_custom_releases.build_flags}
  -D DEVICE_UP1_SEN_8X